### ISSUE TITLE
Uncaught ReferenceError: father is not defined

### ISSUE THREAD

**Issue by jpartain89** [sydro/atom-ansible-vault#11] opened 2017-03-10 08:23 UTC
[Enter steps to reproduce:]

1. Toggle the auto en and decrypt option.

I believe another box is supposed to be present on the settings page, for the ansible-vault binary location, but that option box is not appearing.

![settings](https://cloud.githubusercontent.com/assets/10989696/23787631/8f0013d2-0538-11e7-8ee0-7669f6545e93.png)

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [ansible-vault](https://github.com/sydro/atom-ansible-vault) package 0.4.0

### Stack Trace

Uncaught ReferenceError: father is not defined

```
At /Users/jpartain89/.atom/packages/ansible-vault/lib/ansible-vault-utils.js:96

ReferenceError: father is not defined
    at AnsibleVaultUtils.EnableAuto (ansible-vault-utils.js:96:5)
    at settingsToogle (ansible-vault.js:11:17)
    at /app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
    at SettingsPanel.set (/app.asar/node_modules/settings-view/lib/settings-panel.js:190:19)
    at HTMLInputElement.changeHandler (/app.asar/node_modules/settings-view/lib/settings-panel.js:141:16)
```

### Commands

```
     -1:36.9.0 core:cancel (atom-pane.pane.active)
     -1:36.7.0 settings-view:open (atom-pane.pane.active)
```

### Non-Core Packages

```
ansible-snippets 0.2.0 
ansible-vault 0.4.0 
atom-beautify 0.29.17 
atom-html-preview 0.1.22 
atom-jinja2 0.6.0 
autoclose-html 0.23.0 
autocomplete-ansible 0.1.11 
autocomplete-bash-builtins 0.3.5 
autocomplete-python 1.8.60 
compare-files 0.8.0 
dash 1.7.1 
git-plus 7.3.3 
language-ansible 0.2.1 
language-dotfiles 1.0.0 
language-log 1.8.0 
language-markdown 0.19.1 
language-nginx 0.6.2 
language-restructuredtext 1.0.2 
language-sphinx 0.1.6 
linter 1.11.23 
linter-checkbashisms 0.1.5 
linter-jshint 3.0.3 
linter-markdown 3.1.0 
linter-php 1.3.1 
linter-phpmd 1.5.3 
linter-pylint 1.2.2 
linter-scspell 2.2.0 
linter-shellcheck 1.4.3 
linter-tidy 2.3.0 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.4 
project-manager 3.3.3 
remote-atom 1.3.10 
rst-preview-pandoc 0.1.12 
script 3.14.1 
scroll-through-time 0.2.0 
split-diff 1.2.0 
sync-settings 0.8.1 
travis-ci-status 1.3.1 
wakatime 6.0.13 
```

**Comment by sydro** [comment] 2017-03-10 20:07
I added a fix to make it compatible with atom v1.16 in commit e1bd26d.
I'm trying to reproduce the disappearance of the ansible-vault binary location option box.

**Comment by sydro** [comment] 2017-03-14 13:01
With the last commit is the problem solved?

**Comment by sydro** [comment] 2017-03-15 12:52
I close this issue because it is similar to issue #12

**Closed as completed** 2017-03-15 12:54 UTC
Labels: bug

**Comment by jpartain89** [comment] 2017-03-15 13:03
Sorry, yes this is fixed now.

**Comment by sydro** [comment] 2017-03-15 13:27
No problem :+1:
